- id: '1583117828631'
  alias: Turn on Living room lights
  description: ''
  trigger:
  - entity_id: light.jasco_products_unknown_type_4944_id_3135_level_2
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - scene: scene.living_room_on
- id: '1583117924334'
  alias: Turn Off Living room lights
  description: ''
  trigger:
  - entity_id: light.jasco_products_unknown_type_4944_id_3135_level_2
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - scene: scene.living_room_off
- id: '1583118403252'
  alias: Turn on Kitchen lights
  description: ''
  trigger:
  - entity_id: switch.kitchen_light
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - scene: scene.kitchen_on
- id: '1583118446907'
  alias: Turn off kitchen lights
  description: ''
  trigger:
  - entity_id: switch.kitchen_light
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - scene: scene.kitchen_off
- id: '1583203013701'
  alias: Downstairs on
  description: ''
  trigger:
  - entity_id: light.jasco_products_14294_in_wall_smart_dimmer_level_2
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.br30_rgbw_01
    service: homeassistant.turn_on
  - data: {}
    entity_id: light.a19_rgbw_60_01
    service: homeassistant.turn_on
  - data: {}
    entity_id: light.br30_rgbw_02
    service: homeassistant.turn_on
- id: '1583203106097'
  alias: Downstairs off
  description: ''
  trigger:
  - entity_id: light.jasco_products_14294_in_wall_smart_dimmer_level_2
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.br30_rgbw_01
    service: homeassistant.turn_off
  - data: {}
    entity_id: light.br30_rgbw_02
    service: homeassistant.turn_off
  - data: {}
    entity_id: light.a19_rgbw_60_01
    service: homeassistant.turn_off
- id: '1583203236476'
  alias: Workout Room on
  description: ''
  trigger:
  - entity_id: switch.workout_room_ceiling_light
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - scene: scene.workout_room_on
- id: '1583203269598'
  alias: Workout room off
  description: ''
  trigger:
  - entity_id: switch.workout_room_ceiling_light
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - scene: scene.workout_room_off
- id: '1583204435283'
  alias: Goodnight
  description: ''
  trigger:
  - platform: template
    value_template: ''
  condition: []
  action:
  - scene: scene.kitchen_off
  - scene: scene.living_room_off
  - scene: scene.workout_room_off
  - data: {}
    entity_id: light.jasco_products_14294_in_wall_smart_dimmer_level_2
    service: homeassistant.turn_off
  - data: {}
    entity_id: switch.laundry_room_light
    service: homeassistant.turn_off
  - data: {}
    entity_id: switch.jasco_products_14291_in_wall_smart_switch_switch
    service: homeassistant.turn_off
  - data: {}
    entity_id: zwave.jasco_products_14294_in_wall_smart_dimmer
    service: homeassistant.turn_off
- id: '1583433751537'
  alias: Jen office on
  description: ''
  trigger:
  - entity_id: switch.tim_s_office_wall_switch
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: switch.jasco_products_28169_plug_in_one_outlet_smart_switch_switch_3
    service: homeassistant.turn_on
- id: '1583433802736'
  alias: Jen's office off
  description: ''
  trigger:
  - entity_id: switch.tim_s_office_wall_switch
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: switch.jasco_products_28169_plug_in_one_outlet_smart_switch_switch_3
    service: homeassistant.turn_off
- id: '1583766393990'
  alias: dining room off
  description: ''
  trigger:
  - entity_id: light.jasco_products_unknown_type_4944_id_3135_level
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - device_id: 7275a573764946baab8e7c84b6104216
    domain: switch
    entity_id: switch.kitchen_under_cabinet_lighting
    type: turn_off
- id: '1583766447385'
  alias: Dining Room on
  description: ''
  trigger:
  - entity_id: light.jasco_products_unknown_type_4944_id_3135_level
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - device_id: 7275a573764946baab8e7c84b6104216
    domain: switch
    entity_id: switch.kitchen_under_cabinet_lighting
    type: turn_on
