
homeassistant:
  customize:
    # Add an entry for each entity that you want to overwrite.
    fan.jasco_products_14287_fan_control_switch_level_3:
      friendly_name: "Tim's office"
    fan.jasco_products_14287_fan_control_switch_level:
      friendly_name: "Jen's office fan"
    fan.jasco_products_14287_fan_control_switch_level_2:
      friendly_name: "Master Bedroom Fan"
    light.jasco_products_14294_in_wall_smart_dimmer_level:
      friendly_name: "Upstairs hallway"
    switch.jasco_products_14291_in_wall_smart_switch_switch:
      friendly_name: "Master Bedroom light"
    switch.jasco_products_28169_plug_in_one_outlet_smart_switch_switch_2:
      friendly_name: "Downstairs light"
    switch.jasco_products_28169_plug_in_one_outlet_smart_switch_switch:
      friendly_name: "Board game light"
    switch.jasco_products_28169_plug_in_one_outlet_smart_switch_switch_2:
      friendly_name: "Living Room Corner Light"
    switch.jasco_products_28169_plug_in_one_outlet_smart_switch_switch_3:
      friendly_name: "Jen's office wall plug"
    light.jasco_products_unknown_type_4944_id_3135_level:
      friendly_name: "Dining Room Light"  
    light.jasco_products_unknown_type_4944_id_3135_level_2:
      friendly_name: "Living Room light"
    zwave.jasco_products_unknown_type_4952_id_3137:
      friendly_name: "stair light"
default_config:

  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # http:
  #   base_url: example.duckdns.org:8123
  
# Text to speech
weather:
  - platform: openweathermap
    api_key: !secret openweather
tts:
  - platform: google_translate
light:
  - platform: osramlightify
    host: 10.42.100.108
amcrest:
  - host: 10.42.100.5
    username: admin
    password: !secret amcrest_password
tplink:
  discovery: false
  switch:
    - host: 10.42.100.101
    - host: 10.42.100.102
    - host: 10.42.100.103
    - host: 10.42.100.114
    - host: 10.42.100.115
    - host: 10.42.100.116
    - host: 10.42.100.118
    - host: 10.42.100.119    
    - host: 10.42.100.117
    - host: 10.42.100.127
    - host: 10.42.100.104
    - host: 10.42.100.105
    - host: 10.42.100.106
    - host: 10.42.100.107
    - host: 10.42.100.110     
zwave:
  usb_path: /dev/ttyUSB0
zha:
  database_path: /config/zigbee.db

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
