version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - pipeline:/usr/share/nginx/html
volumes:
  pipeline:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ./html