version: '3'
services:
  home-assistant:
    image: homeassistant/home-assistant:stable
    network_mode: "host" 
    volumes: 
      - ./homeassistant/config:/config
    devices: 
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1        
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
volumes:
  pipeline: