version: '3'
services:
  home-assistant:
    image: homeassistant/home-assistant:stable
    network_mode: "host" 
    volumes: 
      - ./homeassistant/config:/config
      - /etc/localtime:etc/localtime:ro
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
volumes:
  pipeline:
  hassio: